ubuntu_application_sensors: Adapt to Android 7.1 API changes
ubports/platform-api pull request #3
Opened 2018-10-14 14:59 UTC by beidl

Use android::SensorManager::getInstanceForPackage() instead of android::SensorManager::getInstance() and set the event loop name.

2018-10-19 19:05 UTC, APokorny commented
I think you need to enclose the changes in ANDROID_VERSION_MAJOR >= 7 blocks.
Because we will probably build ubp-5.1 system images with that code.

2018-10-19 20:12 UTC, beidl commented
> I think you need to enclose the changes in ANDROID_VERSION_MAJOR >= 7 blocks.
> Because we will probably build ubp-5.1 system images with that code.

Agreed, should build now with 5.1 based device abstractions.

2018-10-19 20:20 UTC, beidl commented
Note: Build failures occur due to installing missing packages via apt

```
Err http://repo.ubports.com PR-3/main arm64 liburl-dispatcher1-dev arm64 0.2+ubports+0~20180611143914.3~1.gbp9a4659

  404  Not Found [IP: 2606:4700:20::6818:9 80]
```

2018-10-19 20:56 UTC, APokorny commented
Yes you can ignore the build error. It is not related to the change. There seems to be something wrong with the o way the armhf build selects the repository fetch the url-dispatcher package from

2018-10-19 22:18 UTC, APokorny commented on android/hybris/ubuntu_application_sensors_for_hybris.cpp
> +#ifdef ANDROID_VERSION_MAJOR >= 7
#if ANDROID_VERSION_MAJOR >= 7

2018-10-19 22:19 UTC, APokorny requested changes

2018-10-19 22:19 UTC, APokorny commented on android/hybris/ubuntu_application_sensors_for_hybris.cpp
> +#ifdef ANDROID_VERSION_MAJOR >= 7
and same below ..

2018-10-20 09:58 UTC, beidl commented on android/hybris/ubuntu_application_sensors_for_hybris.cpp
> +#ifdef ANDROID_VERSION_MAJOR >= 7
alcohol

2018-10-20 10:05 UTC, APokorny approved these changes

2018-10-20 21:06 UTC, merged